name: Generate Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodule shdoc
      run: |
          test -d shdoc || git submodule add https://github.com/reconquest/shdoc.git
          git submodule update -f --init
          ls -la >./log.txt
    - name: Run shdoc
      run: |
        bash -c "./shdoc/shdoc prova.sh >./REFERENCE.md"
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git fetch
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Automated build push" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
